### ISSUE TITLE
Latest dayjs version causes exception in client.messages.create()

### ISSUE THREAD

**Issue by pwiebe** [twilio/twilio-node#934]
### Issue Summary
Calling client.messages.create() using version 1.11.7 of dayjs throws an exception as shown below.  Downgrading to version 1.11.5 resolves the issue.

### Steps to Reproduce
1. send a message using client.messages.create() as shown in the code snippet

### Code Snippet
```
const twilio = require('twilio');
const client = twilio(ACCOUNT_SID, AUTH_TOKEN);

try {
        const result = await client.messages.create({
            to,
            from,
            body,
            statusCallback,
        });
        return result;
} catch (e) {
        console.log(e.message, e.stack);
}
```

### Exception/Log
```
TypeError: Cannot read properties of null (reading 'constructor')
    at M.r (/Users/node_modules/dayjs/plugin/objectSupport.js:1:412)
    at M.parse (/Users//node_modules/dayjs/plugin/objectSupport.js:1:887)
    at new M (/Users/node_modules/dayjs/dayjs.min.js:1:2038)
    at Function.utc (/Users/node_modules/dayjs/plugin/utc.js:1:402)
    at parseDate (/Users/node_modules/twilio/lib/base/deserialize.js:64:29)
    at Object.rfc2822DateTime (/Users/node_modules/twilio/lib/base/deserialize.js:40:12)
    at new MessageInstance (/Users/node_modules/twilio/lib/rest/api/v2010/account/message.js:126:37)
    at /Users/node_modules/twilio/lib/rest/api/v2010/account/message.js:279:63
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Technical details:
* twilio-node version: 4.11.0
* dayjs version: 1.11.7
* node version: 18.15.0

**Comment by AsabuHere** [comment]
Hi @pwiebe, Thanks for the heads up!
I tried reproducing this issue, and this works with the latest version 4.11.0. Can you please try the same code with the latest version of twilio?

**Comment by Amogh-Gopinathan** [comment]
@AsabuHere I'm getting this error 'TypeError: dayjs_1.default.utc is not a function'
\node_modules\twilio\lib\base\deserialize.js:64:29

**Comment by charan678** [comment]
Hello @pwiebe I was checking change logs for dayjs, I found they made changes with objectSupport. People has commented for **null** values issue there. You can have a look into this [link](https://github.com/iamkun/dayjs/commit/c9370ea96bf420439ee7eaa4146e8ed643160312). Let see if they are going to fix this in upcoming releases

**Comment by AsabuHere** [comment]
Hi @titanism, Thanks for raising the PR to update the dayjs version. Our team has reviewed and merged the PR. 

@pwiebe Please verify the fix using the updated version of dayjs, and feel free to open a new github issue if the issue still persists
