### ISSUE TITLE
3.0.0 Node - TypeError: twilio.TwimlResponse is not a function  

### ISSUE THREAD

**Issue by jgberg** [twilio/twilio-node#242]
**Version:**
3.0.0
**API Subdomain (api/taskrouter/ip_messaging):**
sms
### Code Snippet
```javascript
// (coffeescript snippet actually)...
return new Response( twilio.TwimlResponse().toString(), 200, 'xml') 
// now this line fails with:
// TypeError: twilio.TwimlResponse is not a function  
// where is used to work on 2.11.1 and earlier versions of sdk
```
We use this to generate a response back to twilio when it calls into our system when we receive a sms message, so that our endpoint is not marked as failed.

The function has apparently been removed or renamed. We need it to continue to exist in 3.0.0 ...

### Exception / Log
```
<place exception / log here>
```

### Steps to Reproduce
1.
2.
3.

### Feature Request
_If this is a feature request, make sure you search Issues for an existing request before creating a new one!_

**Comment by dylanjt** [comment]
Same issue here.

**Comment by dylanjt** [comment]
@jgberg did some digging.

`twilio.TwimlResponse()` is now `twilio.twiml.MessagingResponse()`.

**Comment by jingming** [comment]
@jgberg @dylanjt thanks for upgrading to the new version!

For the new version of the library, we separated out TwiML into separate classes https://github.com/twilio/twilio-node/blob/master/lib/twiml/VoiceResponse.js and https://github.com/twilio/twilio-node/blob/master/lib/twiml/MessagingResponse.js to reflect what the current types of TwiML there are! 

Let us know if you have anymore questions!

**Comment by jcjaredevans** [comment]
I don't think your QuickStart documentation reflects this: https://www.twilio.com/docs/quickstart/node/programmable-voice#receiving-phone-calls

**Comment by dougdot3** [comment]
The QuickStart guide is incorrect.
