### ISSUE TITLE
Regression: Bulk Exports specific-day `fetch()` returns `void` instead of `DayInstance` in 6.1.0

### ISSUE THREAD

**Issue by gws** [twilio/twilio-node#1207]
# Summary

6.1.0 contains a regression in the Bulk Exports specific-day resource.

`client.bulkexports.v1.exports('Messages').days(day).fetch()` is typed as `Promise<void>` and does not construct a `DayInstance` at runtime. This breaks use of the documented `GET /v1/Exports/{ResourceType}/Days/{Day}` endpoint through the SDK.

# Affected versions

- Works in `twilio` 6.0.2.
- Fails in `twilio` 6.1.0.

# Reproduction

1. Install the dependencies in a fresh project:
   ```sh
   npm install twilio@6.1.0 typescript
   ```
2. Create `index.ts` that calls the helper and accesses its `redirectTo` value:
   ```ts
   import twilio from 'twilio';

   async function main() {
     const client = twilio('ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'auth-token');
     const day = await client.bulkexports.v1.exports('Messages').days('2026-08-01').fetch();
     const url = day.redirectTo;
   }
   ```
3. Compile the file:
   ```sh
   npx tsc --noEmit index.ts
   ```

The compiler reports:

```text
TS2339: Property 'redirectTo' does not exist on type 'void'.
```

This is also a runtime issue: the helper returns the raw parsed API payload rather than a `DayInstance`. JavaScript consumers may receive a payload with the API field name `redirect_to`, but cannot read the SDK property `redirectTo` from its result.

# Expected behavior

`days(day).fetch()` should issue `GET /v1/Exports/{ResourceType}/Days/{Day}` and resolve to a `DayInstance` with properties including `redirectTo`. This is the current documented Node usage for the endpoint: [Bulk Export day resource documentation](https://www.twilio.com/docs/usage/bulkexport/day).

# Actual behavior

In 6.1.0, the specific-day `fetch()` is declared as `Promise<void>` and returns the raw parsed API response rather than a `DayInstance`. The `DayInstance` type still defines `redirectTo`, but the specific-day fetch path does not construct that instance.

# Cause

The 6.1.0 generated specific-day resource declares [`fetch()` as `Promise<void>`](https://github.com/twilio/twilio-node/blob/6.1.0/src/rest/bulkexports/v1/export/day.ts#L61-L80). Its implementation [returns the raw `Version.fetch` result without mapping it to a `DayInstance`](https://github.com/twilio/twilio-node/blob/6.1.0/src/rest/bulkexports/v1/export/day.ts#L111-L127). `Version.fetch` [returns the parsed response body](https://github.com/twilio/twilio-node/blob/6.1.0/src/base/Version.ts#L154-L165), but the specific-day resource's [`fetchWithHttpInfo` explicitly sets `body` to `undefined`](https://github.com/twilio/twilio-node/blob/6.1.0/src/rest/bulkexports/v1/export/day.ts#L130-L145).

The same 6.1.0 file [still declares `redirectTo` on `DayInstance`](https://github.com/twilio/twilio-node/blob/6.1.0/src/rest/bulkexports/v1/export/day.ts#L182-L202).

In 6.0.2, the equivalent code [declares a `DayInstance` result](https://github.com/twilio/twilio-node/blob/6.0.2/src/rest/bulkexports/v1/export/day.ts#L61-L82) and [maps the response payload into that instance](https://github.com/twilio/twilio-node/blob/6.0.2/src/rest/bulkexports/v1/export/day.ts#L113-L139).

# Impact

For TypeScript consumers, this causes a compile failure when accessing `DayInstance` fields such as `redirectTo`.

For JavaScript consumers, it returns a raw payload rather than the SDK day object and therefore causes a runtime mismatch.
